MCU = RP2040

BOARD = GENERIC_RP_RP2040

BOOTLOADER = rp2040

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

BOOTMAGIC_ENABLE = yes